### ISSUE TITLE
Do not use on_delete=models.PROTECT

### ISSUE THREAD

**Issue by m1kola** [cca/libraries_wagtail#36]
There are few issues with `on_delete=models.PROTECT` support in Wagtail:

* https://github.com/wagtail/wagtail/issues/1602 - Wagtail doesn't give an editor proper explanation of an error when the editor deletes a protected entry
* https://github.com/wagtail/wagtail/issues/3658 - A page tree can be broken in some rare cases. I didn't manage to find protected links *to* pages. There are some links *from* pages to images and to `hours.Library` which shouldn't break the page tree. So probably it's not an issue for CCA Libraries.

**Comment by phette23** [comment]
Hmm I didn't know about these issues. I originally was using `SET_NULL` but I deliberately changed to using `PROTECT` in 13aabeaf2091d43c79a348ded6851e3d82560a5c because we were able to delete images that were in use; people could go to the Images section in the admin UI and delete an image that was being used on a page. `PROTECT` seemed to fix that.

We can avoid protected links to pages, so 3658 isn't a huge problem. And I think, given the choice, I'd rather have editors not able to delete images still, even if they don't get a proper error.
